const services = [
 {id:'gestion',name:'Implementación de Sistemas de Gestión',category:'Operaciones mineras',place:'Ambos',icon:'clipboard-check',description:'Consultoría externa y outsourcing para diseñar, documentar, capacitar y auditar sistemas bajo normas internacionales.',tags:['ISO 9001','ISO 14001','ISO 45001','Ley 29783','ISO 37001'],benefits:['Enfoque en el core business','Experticia inmediata','Optimización de costos','Reducción de riesgos'],match:['seguridad','auditoria','ambiental']},
 {id:'topografia',name:'Levantamiento Topográfico',category:'Operaciones mineras',place:'Ambos',icon:'ruler',description:'Medición, control geométrico y modelamiento técnico para proyectos superficiales y subterráneos.',tags:['Drones UAV','LiDAR','GNSS','Escaneo láser 3D'],benefits:['Información precisa','Control de volúmenes','Avances trazables'],match:['medicion','superficie','subterraneo']},
 {id:'sostenimiento',name:'Perforación, Voladura y Sostenimiento',category:'Operaciones mineras',place:'Subterráneo',icon:'drill',description:'Excavación en roca con fragmentación eficiente y fortificación geomecánica para estabilidad total.',tags:['Shotcrete','Pernos','Mallas','Voladura controlada'],benefits:['Estabilidad geomecánica','Avance seguro','Precisión de excavación'],match:['infraestructura','subterraneo','emergencia']},
 {id:'operaciones',name:'Operaciones Integrales de Mina',category:'Operaciones mineras',place:'Ambos',icon:'factory',description:'Gestión, supervisión y ejecución completa de actividades mineras superficiales y subterráneas.',tags:['Gestión','Supervisión','Ejecución'],benefits:['Operación coordinada','Mayor control','Continuidad'],match:['operaciones','continuidad','permanente']},
 {id:'senaletica',name:'Señaléticas Industriales',category:'Operaciones mineras',place:'Ambos',icon:'signpost',description:'Diseño y elaboración de señalizaciones normadas para seguridad, tránsito y evacuación.',tags:['Seguridad','Tránsito','Evacuación'],benefits:['Entornos visibles','Cumplimiento normativo','Prevención'],match:['seguridad','superficie','auditoria']},
 {id:'ventilacion',name:'Redes de Ventilación',category:'Sistemas auxiliares',place:'Subterráneo',icon:'wind',description:'Diseño e instalación de ventilación principal y secundaria para condiciones óptimas de trabajo.',tags:['Ventilación principal','Aire limpio','Interior mina'],benefits:['Aire limpio','Seguridad del personal','Continuidad operacional'],match:['continuidad','subterraneo','emergencia']},
 {id:'bombeo',name:'Sistema de Bombeo y Drenaje',category:'Sistemas auxiliares',place:'Subterráneo',icon:'waves',description:'Evacuación y gestión eficiente del agua subterránea para proteger la operación.',tags:['Drenaje','Gestión hídrica','Bombeo'],benefits:['Control de infiltraciones','Protección operacional','Menos paradas'],match:['continuidad','subterraneo','emergencia']},
 {id:'soldadura',name:'Soldadura Industrial',category:'Sistemas auxiliares',place:'Ambos',icon:'wrench',description:'Servicios especializados para estructuras, mantenimiento mecánico y tuberías de alta presión.',tags:['Estructuras','Mantenimiento','Tuberías'],benefits:['Uniones confiables','Atención especializada'],match:['mantenimiento','infraestructura','continuidad']},
 {id:'civil-superficie',name:'Construcción Civil en Superficie Mina',category:'Obras civiles',place:'Superficie',icon:'building-2',description:'Infraestructura de soporte en campamentos, plantas y áreas administrativas.',tags:['Campamentos','Plantas','Administración'],benefits:['Infraestructura funcional','Adaptación al proyecto'],match:['infraestructura','superficie','nuevo']},
 {id:'carpinteria',name:'Carpintería Industrial',category:'Obras civiles',place:'Subterráneo',icon:'hammer',description:'Elaboración y habilitado de cuadros de madera técnica para fortificación tradicional.',tags:['Cuadros de madera','Fortificación','Galerías'],benefits:['Soporte técnico','Adaptación a galerías'],match:['infraestructura','subterraneo']},
 {id:'civil-interior',name:'Construcción Civil Interior Mina',category:'Obras civiles',place:'Subterráneo',icon:'hard-hat',description:'Construcción de muros de contención, cámaras de bombeo e infraestructura subterránea.',tags:['Muros','Cámaras de bombeo','Interior mina'],benefits:['Infraestructura robusta','Resistencia'],match:['infraestructura','subterraneo','nuevo']},
 {id:'residuos',name:'Gestión y Manejo de Residuos',category:'Gestión ambiental',place:'Ambos',icon:'recycle',description:'Recolección, segregación y gestión responsable de residuos de la operación.',tags:['Segregación','Recolección','Economía circular'],benefits:['Cumplimiento ambiental','Gestión responsable'],match:['ambiental','seguridad','auditoria']},
 {id:'compra-residuos',name:'Compra y Venta de Residuos',category:'Gestión ambiental',place:'Ambos',icon:'refresh-cw',description:'Comercialización autorizada de residuos sólidos reaprovechables.',tags:['Reaprovechamiento','Valorización'],benefits:['Economía circular','Gestión autorizada'],match:['ambiental']},
 {id:'transporte',name:'Transporte',category:'Servicios complementarios',place:'Ambos',icon:'truck',description:'Soporte de transporte para la operación, personal e insumos.',tags:['Logística','Traslado'],benefits:['Coordinación logística','Disponibilidad'],match:['personal','permanente','continuidad']},
 {id:'lavanderia',name:'Lavandería',category:'Servicios complementarios',place:'Campamento',icon:'shirt',description:'Servicio de lavandería para personal y operación en campamento.',tags:['Campamento','Bienestar'],benefits:['Soporte al personal'],match:['personal','campamento','permanente']},
 {id:'hoteleria',name:'Hotelería',category:'Servicios complementarios',place:'Campamento',icon:'bed-double',description:'Alojamiento y soporte de hospitalidad para equipos de trabajo.',tags:['Alojamiento','Campamento'],benefits:['Bienestar del personal'],match:['personal','campamento','permanente']},
 {id:'reclutamiento',name:'Reclutamiento de Personal',category:'Servicios complementarios',place:'Ambos',icon:'users',description:'Selección y provisión de personal para distintos frentes de operación.',tags:['Selección','Personal operativo'],benefits:['Cobertura de posiciones','Agilidad'],match:['personal','nuevo','permanente']},
 {id:'ssoma',name:'Capacitaciones de SSOMA',category:'Servicios complementarios',place:'Ambos',icon:'graduation-cap',description:'Capacitaciones de seguridad, salud ocupacional y medio ambiente.',tags:['SSOMA','Capacitación','Prevención'],benefits:['Cultura preventiva','Personal preparado'],match:['seguridad','personal','auditoria']}
];
const questions=[
 {key:'area',title:'¿En qué área requiere apoyo?',description:'Elige el frente principal de tu necesidad.',single:true,options:[['operaciones','Operaciones mineras','Producción, control y ejecución','pickaxe'],['auxiliares','Sistemas auxiliares','Ventilación, bombeo y mantenimiento','settings'],['civiles','Obras civiles subterráneas','Infraestructura y fortificación','construction'],['ambiental','Gestión ambiental','Residuos y cumplimiento','leaf'],['personal','Servicios complementarios','Talento, logística y campamento','briefcase-business']]},
 {key:'ubicacion',title:'¿Dónde se desarrollará el trabajo?',description:'Esto nos ayuda a elegir soluciones adaptadas al entorno.',single:true,options:[['superficie','Superficie','Planta, terreno o instalaciones externas','mountain'],['subterraneo','Interior mina / subterráneo','Galerías, túneles o tajos','door-open'],['ambos','Ambos','Trabajo en superficie e interior mina','git-branch'],['campamento','Instalaciones o campamento','Alojamiento y áreas de soporte','tent-tree']]},
 {key:'prioridades',title:'¿Cuál es la prioridad principal?',description:'Puedes seleccionar una o varias prioridades.',single:false,options:[['seguridad','Seguridad y cumplimiento','Gestión preventiva y normativa','shield-check'],['continuidad','Continuidad operacional','Mantener el ritmo de producción','activity'],['infraestructura','Infraestructura y construcción','Obras, soporte y fortificación','building'],['medicion','Levantamiento técnico y medición','Datos geométricos y modelamiento','ruler'],['ambiental','Gestión ambiental','Residuos y sostenibilidad','leaf'],['personal','Personal, capacitación o servicios generales','Equipos y bienestar','users']]},
 {key:'necesidad',title:'¿Qué tipo de necesidad tiene?',description:'Selecciona el contexto actual de tu proyecto.',single:true,options:[['nuevo','Proyecto nuevo','Inicio o ampliación de operación','rocket'],['mantenimiento','Mantenimiento','Mejoras, reparación o conservación','wrench'],['emergencia','Emergencia operativa','Atención prioritaria','siren'],['auditoria','Auditoría, certificación o cumplimiento','Evaluación de conformidad','file-check-2'],['permanente','Operación permanente','Soporte continuo para la operación','repeat-2']]}
];
let step=0; const answers={area:null,ubicacion:null,prioridades:[],necesidad:null};
const qContent=document.getElementById('questionContent'); const nextBtn=document.getElementById('nextBtn'); const backBtn=document.getElementById('backBtn');
function renderIcons(){if(window.lucide)lucide.createIcons()}
function renderQuestion(){const q=questions[step];qContent.innerHTML=`<div><p class="eyebrow">${q.single?'SELECCIONA UNA OPCIÓN':'SELECCIONA TODAS LAS QUE APLIQUEN'}</p><h3 class="question-title">${q.title}</h3><p class="question-description">${q.description}</p><div class="option-grid">${q.options.map(([value,label,desc,icon])=>{const selected=q.single?answers[q.key]===value:answers[q.key].includes(value);return `<button type="button" class="option ${selected?'selected':''}" data-value="${value}"><span class="option-icon"><i data-lucide="${icon}"></i></span><span>${label}<small>${desc}</small></span></button>`}).join('')}</div></div>`;qContent.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{const val=btn.dataset.value;if(q.single)answers[q.key]=val;else answers[q.key]=answers[q.key].includes(val)?answers[q.key].filter(x=>x!==val):[...answers[q.key],val];renderQuestion()});nextBtn.innerHTML=step===3?'Ver recomendaciones <i data-lucide="sparkles"></i>':'Continuar <i data-lucide="arrow-right"></i>';backBtn.disabled=step===0;document.getElementById('sideStep').textContent=`Paso ${step+1} de 4`;document.getElementById('progressBar').style.width=`${(step+1)*25}%`;document.querySelectorAll('#stepList li').forEach((li,i)=>li.classList.toggle('active',i===step));renderIcons()}
nextBtn.onclick=()=>{const q=questions[step];const valid=q.single?answers[q.key]:answers[q.key].length;if(!valid){qContent.querySelector('.question-description').textContent='Selecciona al menos una opción para continuar.';return}if(step<3){step++;renderQuestion()}else showResults()};backBtn.onclick=()=>{if(step>0){step--;renderQuestion()}};
function getRecommendations(){const tokens=[answers.area,answers.ubicacion,answers.necesidad,...answers.prioridades].filter(Boolean);return services.map(s=>({...s,score:s.match.reduce((n,x)=>n+(tokens.includes(x)?1:0),0)+(s.place==='Ambos'?0.2:0)})).filter(s=>s.score>0).sort((a,b)=>b.score-a.score).slice(0,5)}
function serviceCard(s,recommended=false){return `<article class="${recommended?'recommend-card':'service-card'}"><span class="service-category">${s.category}</span>${recommended?`<span class="score">${Math.round(s.score*20)}% AFINIDAD</span>`:''}<h3>${s.name}</h3><p>${s.description}</p><div class="tags">${s.tags.slice(0,4).map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="card-actions"><button data-detail="${s.id}">Ver detalles</button><button class="quote" data-quote="${s.id}">Solicitar cotización →</button></div></article>`}
function showResults(){const results=getRecommendations();document.getElementById('recommendations').innerHTML=results.map(s=>serviceCard(s,true)).join('')||`<p>No encontramos coincidencias exactas. Explora nuestro catálogo completo.</p>`;document.getElementById('resultSummary').textContent=`Encontramos ${results.length} solución${results.length!==1?'es':''} que se ajustan a las condiciones que indicaste.`;document.getElementById('resultSection').classList.remove('hidden');document.getElementById('resultSection').scrollIntoView({behavior:'smooth'});bindCardActions();renderIcons()}
document.getElementById('restartBtn').onclick=()=>{step=0;Object.assign(answers,{area:null,ubicacion:null,prioridades:[],necesidad:null});document.getElementById('resultSection').classList.add('hidden');renderQuestion();document.getElementById('evaluacion').scrollIntoView({behavior:'smooth'})};
let filter='Todos';function renderCatalog(){const term=document.getElementById('searchInput').value.toLowerCase();const items=services.filter(s=>(filter==='Todos'||s.category===filter)&&`${s.name} ${s.description} ${s.tags.join(' ')}`.toLowerCase().includes(term));document.getElementById('serviceGrid').innerHTML=items.map(s=>serviceCard(s)).join('')||'<p>No hay servicios que coincidan con la búsqueda.</p>';bindCardActions();renderIcons()}
function bindCardActions(){document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openModal(x.dataset.detail));document.querySelectorAll('[data-quote]').forEach(x=>x.onclick=()=>{document.getElementById('serviceSelect').value=x.dataset.quote;document.getElementById('contacto').scrollIntoView({behavior:'smooth'})})}
function openModal(id){const s=services.find(x=>x.id===id);document.getElementById('modalContent').innerHTML=`<p class="service-category">${s.category} · ${s.place}</p><h2 id="modalTitle">${s.name}</h2><p>${s.description}</p><div class="modal-section"><h4>Capacidades</h4><div class="tags">${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="modal-section"><h4>Beneficios principales</h4><ul>${s.benefits.map(b=>`<li>${b}</li>`).join('')}</ul></div><div class="modal-section"><h4>Aplicación recomendada</h4><p>Ideal para operaciones en <strong>${s.place.toLowerCase()}</strong>, con enfoque en una ejecución segura, eficiente y controlada.</p></div><button class="button button-primary" data-quote-modal="${s.id}">Solicitar cotización <i data-lucide="arrow-right"></i></button>`;document.getElementById('detailModal').classList.remove('hidden');document.querySelector('[data-quote-modal]').onclick=()=>{document.getElementById('detailModal').classList.add('hidden');document.getElementById('serviceSelect').value=s.id;document.getElementById('contacto').scrollIntoView({behavior:'smooth'})};renderIcons()}
document.getElementById('modalClose').onclick=()=>document.getElementById('detailModal').classList.add('hidden');document.getElementById('detailModal').onclick=e=>{if(e.target.id==='detailModal')e.currentTarget.classList.add('hidden')};
const cats=['Todos',...new Set(services.map(s=>s.category))];document.getElementById('categoryFilters').innerHTML=cats.map(c=>`<button class="chip ${c==='Todos'?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});document.getElementById('searchInput').oninput=renderCatalog;
document.getElementById('serviceSelect').innerHTML='<option value="">Selecciona un servicio</option>'+services.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');document.getElementById('contactForm').onsubmit=e=>{e.preventDefault();document.getElementById('formStatus').textContent='Solicitud registrada. Nos comunicaremos contigo a la brevedad.';e.target.reset()};
renderQuestion();renderCatalog();renderIcons();
